# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DHnuAhmBEfOZWdlqwmlmc-jAjmo_HQ1o
"""

from cProfile import run
import pandas as pd
import plotly.express as px
import streamlit as st

#st run codigoBase.py

#LENDO A TABELA
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')
#MELHORANDO O NOME DAS TABELAS
df = df.rename(columns={'newDeaths': 'Novos Óbitos', 'newCases': 'Novos Casos', 'deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes', 'totalCases_per_100k_inhabitants': 'Casos por 100 mil habitantes'})
#SELEÃO DO ESTADO
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Qual o estado', estados) #sidebar deixa a informação no menu lateral
#SELEÇÃO DA COLUNA
colunas = ['Novos Óbitos', 'Novos Casos', 'Óbitos por 100 mil habitantes', 'Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)
#SELEÇÃO DAS LINHAS QUE PERTENCEM AO ESTADO
df = df[df['state'] == state]

fig = px.line(df, x="date", y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('DADOS COVID BRASIL')
st.write('Nessa aplicação, o usuário tem a opção de escolher  o estado e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos a partir do site: https://github.com/wcota/covid19br')
